# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lebray/Vivado-Workflow-Scripts/HW4T3_4/vivado_project/HW4T3_4.srcs/sources_1/ip/myRom/myRom.xci
# IP: The module: 'myRom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lebray/Vivado-Workflow-Scripts/HW4T3_4/vivado_project/HW4T3_4.srcs/sources_1/ip/myRom/myRom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myRom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/lebray/Vivado-Workflow-Scripts/HW4T3_4/vivado_project/HW4T3_4.srcs/sources_1/ip/myRom/myRom.xci
# IP: The module: 'myRom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lebray/Vivado-Workflow-Scripts/HW4T3_4/vivado_project/HW4T3_4.srcs/sources_1/ip/myRom/myRom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myRom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
